<?php
/**
 * Deicer Framework (http://github.com/alex-butucea/deicerframework)
 *
 * @link       http://github.com/alex-butucea/deicerframework for canonical source repository
 * @copyright  2013 Alex Butucea <alex826@gmail.com>
 * @license    The MIT License (MIT) {@link http://opensource.org/licenses/MIT}
 */

namespace Deicer\Query\Message;

use Deicer\Query\InvariableQueryInterface;
use Deicer\Query\Message\QueryMessageInterface;

/**
 * Interface for execution messages generated by invariable queries
 *
 * @category   Deicer
 * @package    Query
 * @subpackage Message
 * @version    $id$
 * @copyright  2013 Alex Butucea <alex826@gmail.com>
 * @author     Alex Butucea <alex826@gmail.com>
 * @license    The MIT License (MIT) {@link http://opensource.org/licenses/MIT}
 */
interface InvariableQueryMessageInterface extends
 QueryMessageInterface
{
    /**
     * String serialization format
     * 
     * @const string
     */
    const SERIALIZED_FORMAT = 'Invariable Query Execution: %s | Result: "%s" | Elapsed Time: %dms | Content: %s';

    /**
     * Invariable query constructor
     *
     * @throws NonStringException If $topic is not a string
     * @param  string $topic See constants in QueryMessageInterface
     * @param  mixed $content Content returned from the query's inner execution
     * @param  TokenizedQueryInterface $publisher Message originator
     * @return InvariableQueryMessageInterface
     */
    public function __construct(
        $topic,
        $content,
        InvariableQueryInterface $publisher
    );
}
